<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [Default suite]" duration-ms="152493" started-at="2020-02-09T04:11:30Z" finished-at="2020-02-09T04:14:03Z">
    <groups>
    </groups>
    <test name="Default test(failed)" duration-ms="152493" started-at="2020-02-09T04:11:30Z" finished-at="2020-02-09T04:14:03Z">
      <class name="br.com.rsinet.mobile.appium.testes.TesteCadastro">
        <test-method status="PASS" signature="report()[pri:0, instance:br.com.rsinet.mobile.appium.testes.TesteCadastro@148080bb]" name="report" is-config="true" duration-ms="557" started-at="2020-02-09T04:11:30Z" finished-at="2020-02-09T04:11:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- report -->
        <test-method status="PASS" signature="before()[pri:0, instance:br.com.rsinet.mobile.appium.testes.TesteCadastro@148080bb]" name="before" is-config="true" duration-ms="35691" started-at="2020-02-09T04:11:31Z" finished-at="2020-02-09T04:12:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="FAIL" signature="cadastro1Valido()[pri:0, instance:br.com.rsinet.mobile.appium.testes.TesteCadastro@148080bb]" name="cadastro1Valido" duration-ms="31887" started-at="2020-02-09T04:12:07Z" finished-at="2020-02-09T04:12:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at br.com.rsinet.mobile.appium.testes.TesteCadastro.cadastro1Valido(TesteCadastro.java:76)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cadastro1Valido -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:br.com.rsinet.mobile.appium.testes.TesteCadastro@148080bb]" name="afterMethod" is-config="true" duration-ms="8369" started-at="2020-02-09T04:12:39Z" finished-at="2020-02-09T04:12:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=cadastro1Valido status=FAILURE method=TesteCadastro.cadastro1Valido()[pri:0, instance:br.com.rsinet.mobile.appium.testes.TesteCadastro@148080bb] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="before()[pri:0, instance:br.com.rsinet.mobile.appium.testes.TesteCadastro@148080bb]" name="before" is-config="true" duration-ms="37655" started-at="2020-02-09T04:12:47Z" finished-at="2020-02-09T04:13:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="PASS" signature="cadastro2Invalido()[pri:0, instance:br.com.rsinet.mobile.appium.testes.TesteCadastro@148080bb]" name="cadastro2Invalido" duration-ms="30721" started-at="2020-02-09T04:13:25Z" finished-at="2020-02-09T04:13:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cadastro2Invalido -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:br.com.rsinet.mobile.appium.testes.TesteCadastro@148080bb]" name="afterMethod" is-config="true" duration-ms="7479" started-at="2020-02-09T04:13:55Z" finished-at="2020-02-09T04:14:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=cadastro2Invalido status=SUCCESS method=TesteCadastro.cadastro2Invalido()[pri:0, instance:br.com.rsinet.mobile.appium.testes.TesteCadastro@148080bb] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="finalizareport()[pri:0, instance:br.com.rsinet.mobile.appium.testes.TesteCadastro@148080bb]" name="finalizareport" is-config="true" duration-ms="77" started-at="2020-02-09T04:14:03Z" finished-at="2020-02-09T04:14:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finalizareport -->
      </class> <!-- br.com.rsinet.mobile.appium.testes.TesteCadastro -->
    </test> <!-- Default test(failed) -->
  </suite> <!-- Failed suite [Default suite] -->
</testng-results>
